spring:
  application:
    name: idmhperu

  datasource:
    url: jdbc:mysql://31.97.133.166:3306/idmhperu_test
    username: user-idmhperu
    password: Secretoidmh2026.
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 41

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 30
        jdbc:
          batch_size: 30
          order_inserts: true
          order_updates: true
      #format_sql: true

  jackson:
    time-zone: America/Lima

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8090

jwt:
  secret:
    key: 6EAB10E2B4F3AASDG912F9C32C73F0AH41J21A9F5FCE3C423F6D489E7BA84DA82

custom:
  server:
    hostname: http://localhost:8090

sunat:
  url: https://e-fact.facturacion-idmhperu.website/facturador/sunat/comprobante/sent
  url-guia: https://e-fact.facturacion-idmhperu.website/facturador/sunat/guia/sent
  url-guia-valid: https://e-fact.facturacion-idmhperu.website/facturador/sunat/guia/valid
  #  url: http://localhost:8889/facturador/sunat/comprobante/sent
  #  url-guia: http://localhost:8889/facturador/sunat/guia/sent
  #  url-guia-valid: http://localhost:8889/facturador/sunat/guia/valid

recaptcha:
  secret:
    key: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
  min:
    score: 0.5
  bypass:
    enabled: true

drive:
  folder-id:
    boletas: 1nExlXyuo7YhZuGzdhFS-f0iOExRrZiuM
    facturas: 1P97mI8fDiiEmWaA5-0ksQRZ7FDn51ELm
    notas: 1K7nhl2f5KRLU8GIwZGTTZcFyLCSj886N
    guias: 1fHrc65lfhV3VRD752M8p33X5WkoHJI8z
    pagos: 1hAPzYvfsLAoqI5zvET2PQBUtlCZCGojO
    productos-imagenes: 1uN4p_hngvHzckRJ8Q9rrHp-bq0lXlRNW
    productos-fichas: 1aif-JgqRT-4jtHfAfoM61FU4sNnxyEOn
    servicios-imagenes: 1KYnqBxDvxPBTXoMikfDX6WyHmjGW-aHz
    servicios-fichas: 1sEjZWMa8A6__rtRdDy8j2lGb_RL08APN