spring:
  application:
    name: idmhperu

  datasource:
    url: jdbc:mysql://31.97.133.166:3306/idmh_peru
    username: user-idmhperu
    password: Secretoidmh2026.
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 42

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 30
        jdbc:
          batch_size: 30
          order_inserts: true
          order_updates: true
      #format_sql: true

  jackson:
    time-zone: America/Lima

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8090

jwt:
  secret:
    key: 6EAB10E2B4F3AASDG912F9C32C73F0AH41J21A9F5FCE3C423F6D489E7BA84DA82

custom:
  server:
    hostname: https://api.facturacion-idmhperu.website

sunat:
  url: https://e-fact.facturacion-idmhperu.website/facturador/sunat/comprobante/sent
  url-guia: https://e-fact.facturacion-idmhperu.website/facturador/sunat/guia/sent
  url-guia-valid: https://e-fact.facturacion-idmhperu.website/facturador/sunat/guia/valid

recaptcha:
  secret:
    key: 6Lcwa9EsAAAAAGOKG_i4jHuvZffpDhJkssSMbaJ1
  min:
    score: 0.5
  bypass:
    enabled: false

drive:
  folder-id:
    boletas: 1yusLxBluqIE7jWgB3yVpjDRyG9kgd6KA
    facturas: 1wNhSpzBt9Fy8oABGAeQErcJWly5TYnjn
    notas: 1rb4EDFrl_F6mH5cbXopjz-9I1T1-mONr
    guias: 1t0IXpEwBqNny7MtpM1_nAOxCjmmBDz7Q
    pagos: 10SsxbczLrzxF2OQhgNhk5bzsgOqngRw4
    productos-imagenes: 1tszhtLv2iuaAmicHEDG6_EeVmVp9fwm0
    productos-fichas: 1I0XCXqOCjr-60omKfcALmcJh6R6b_tw7
    servicios-imagenes: 1fblQF0eEOlVWApU4UD20RfI7jL4GVsqj
    servicios-fichas: 1QYoztcjsAS8zTj8TeLoWI_oF_QVToXNR