spring:
  application:
    name: idmhperu

  datasource:
    url: jdbc:mysql://31.97.133.166:3306/idmh_peru
    username: user-idmhperu
    password: Secretoidmh2026.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
      #format_sql: true

  jackson:
    time-zone: America/Lima

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8091

jwt:
  secret:
    key: 6EAB10E2B4F3AASDG912F9C32C73F0AH41J21A9F5FCE3C423F6D489E7BA84DA82

custom:
  server:
    hostname: https://api.facturacion-idmhperu.website

sunat:
  url: https://e-fact.facturacion-idmhperu.website/facturador/sunat/comprobante/sent
  url-guia: https://e-fact.facturacion-idmhperu.website/facturador/sunat/guia/sent

drive:
  folder-id:
    boletas: 12-tPZ-j4uxeEKfn23NnAzjmI1YK1hJmc
    facturas: 1_sFiHA6vWLWC_734WYpZHwrQIs6gxTBV
    notas: 1XIVR71JlNibikBsWa17QUvxkJwLVmriL
    guias: 1g0RoJy7bOZHm2QZNDR0Aj2PCNC_uLrWF
    pagos: 1WxoimdgoNpLv8RzVBp7dw1FiRmw1If7Q
    productos-imagenes: 1pLY9IhKMW9PVafZdF36R25OFvnYm8NfV
    productos-fichas: 1Olt13aygYgHD6n1dmgcDtDPppHv7yNe4
    servicios-imagenes: 14JrSq9-pLKvs632b3rP6zUY2BBDGgKMTY
    servicios-fichas: 18d3DUwI6fc-ptJYUKJXToOe5FbMzGTJM